class CONSTANTS:
    VERSION = "1.2.1-260127-beta"
    PACKVER = "1.2-rev1"
    INITIAL_SCRSIZE = [1536,864]
    TICK_SPEED = 60
class DEBUG:
    ...
class GENERAL:
    SPEED_DACAY = 0.95
    BG_COLOR = [0,0,30]
    ALPHA_DACAY = 3
class GALAXY:
    VISIBLE_DISTANCE = 836.66
    LINE_COLOR = [255,255,255]
    LINE_SHOW_FACTOR = 360
    LABEL_DISPSIZE = 100
    LABEL_COLOR = [109,158,235]
    LABEL_SHOW_FACTOR = 255
class STAR:
    RADIUS = 15
    RADIUS_FACTOR = 1.3
    COLOR = [255,255,255]
    LOCKED_COLOR = [128,128,128]
    SHOW_FACTOR = 360
    class HOVER:
        TICK = 30
        SPEED = 0.2
        REG_FACTOR = (1 - 1 / (SPEED * TICK + 1))
class MOUSE:
    COLOR = [255,255,255]
class AUTOPLAY:
    ENABLE = False
    SCROLL_BG_FACTOR = 0.2
    class TIME:
        MOVEMOUSE = 1
        FADE = 1.5
        CACHE = 0.5
    class MOUSE:
        TICK = None
        SPEED = 0.1
        REG_FACTOR = None
from properties import *
AUTOPLAY.MOUSE.TICK = (AUTOPLAY.TIME.MOVEMOUSE + AUTOPLAY.TIME.FADE - AUTOPLAY.TIME.CACHE) * CONSTANTS.TICK_SPEED
AUTOPLAY.MOUSE.REG_FACTOR = (1 - 1 / (AUTOPLAY.MOUSE.SPEED * AUTOPLAY.MOUSE.TICK + 1))