from ca import *
from entity.entity import Entity
class DataProvider(Interface):
    datrman = Entity.ResourceManager()
    def load_logo(self) -> tuple[Entity.Resource_id,Entity.Resource_id]:...
    def load_data(self) -> None:...
    def tick(self) -> None|Entity.ResourceManager:...
    def resource(self,name:str) -> Entity.Resource_id:...