from ca import *
class CONSTANTS(Wrapper):
    ...
class GALAXY(Wrapper):
    ...
class STAR(Wrapper):
    ...
class HANDLER(Wrapper):
    ...
class CONTROLLER(Wrapper):
    ...
class GENERAL(Wrapper):
    ...